- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonGun.cs
[Jira](https://bradleycapstone.atlassian.net/browse/LV-515?atlOrigin=eyJpIjoiMDc1OGIwM2YzMzE2NGRkZThlZDA1NzgwNmVlYjNmMTUiLCJwIjoiaiJ9)
Minor change so harpoon uses the correct sfx vars
> Vs eng harpoon plays wrong sfx lv 515

- Assets/GameAssets/Boss/BossScripts/Attacks/BossAttackActSystem.cs
- Assets/GameAssets/Boss/BossScripts/WeakPoints/WeakPoint.cs
- Assets/GameAssets/Boss/BossScripts/WeakPoints/WeakPointHandler.cs
- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonGun.cs
- Assets/GameAssets/Player/PlayerScripts/PlayerHealth.cs
- Assets/GameAssets/Player/PlayerScripts/PlayerMovementController.cs
- Assets/GameAssets/World/WorldScripts/Boat/BoatGeometryHealth.cs
- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
- Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/RuntimeSfxManager.cs
[Jira](https://bradleycapstone.atlassian.net/browse/LV-407)
- Properly released the sound instance
- Removed unnecessary movement toggle code
> vs-eng-Fixed-Footsteps-LV-407

- Assets/General/Prefabs/DesignPlayerPackage.prefab
- Assets/General/Prefabs/PlayerHUDCanvas.prefab
- Assets/General/Scenes/BuildScenes/GameScene.unity
also cleaned up strange duplicate heart objects that were invisible in scene
> reordered objects in prefab

- Assets/GameAssets/Boss/BossPrefabs/Attacks/AttackManager.prefab
- Assets/General/Scenes/BuildScenes/GameScene.unity
Variable got unassigned in the merge or something. I just put it back
> Vs-eng-fixingpostmergeissues

- Assets/GameAssets/Player/PlayerPrefabs/PlayerKit.prefab
- Assets/GameAssets/Player/PlayerScripts/PlayerHealth.cs
- Assets/GameAssets/Player/PlayerTestGyms/PlayerHealInteractableGym.unity
- Assets/GameAssets/Player/PlayerTestGyms/PlayerHealInteractableGym.unity.meta
- Assets/GameAssets/World/WorldPrefabs/PlayerInteractables.meta
- Assets/GameAssets/World/WorldPrefabs/PlayerInteractables/HealthPack.prefab
- Assets/GameAssets/World/WorldPrefabs/PlayerInteractables/HealthPack.prefab.meta
- Assets/GameAssets/World/WorldScripts/Interactables/HealthPackInteractable.cs
- Assets/GameAssets/World/WorldScripts/Interactables/HealthPackInteractable.cs.meta
- Assets/General/Scripts/Health/BaseHealth.cs
Created a Healing Pack prefab that can be interacted with to heal the player.
You can test this in the PlayerHealInteractableGym in the editor.
Jira Task: https://bradleycapstone.atlassian.net/browse/LV-402?atlOrigin=eyJpIjoiOTQwOTIxZmUzODNmNGE3NzhkOTNiMTk3MGU4ZjM3OGMiLCJwIjoiaiJ9
Documentation: https://docs.google.com/document/d/1qyV8T-uRBneLjsCzB8W84C3wD3FJ1SjfEBJIeWANhbo/edit?tab=t.aqukfx277tdv
> vs-eng-healing-over-time-lv-402

- Assets/General/Audio/FMODScripts/FmodAmbienceEvents.cs
- Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AmbienceManager.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-420
Adjusted the AmbienceManager and FmodAmbienceEvents to be more in line with the other managers. I don't have start in any other managers, reason being is that the core manager for both the universal manager and gameplay manager call SetUpMainManager on all their associated managers. Also adjusted the FmodAmbienceManager to set up the instance similarly to the managers.
There is an error with the interactables system. Ignore that it will be fixed elsewhere
Also this task is number 420. That's the weed number. I have the humor of a child
> vs-eng-Cleanup-on-the-ambience-manager-LV-420

- Assets/General/Scripts/UniversalFunctions/ObjectSpawner.cs
- Assets/General/Scripts/UniversalFunctions/ObjectSpawner.cs.meta
Gives multiple ways to spawn in an object:
- Serialized fields for in-editor use
- Function overrides to call it outside of the script
Both allow for spawning with or without a parent
> vs-eng-Public-method-to-spawn-a-game-object-LV-521

- Assets/GameAssets/Boss/BossScripts/Attacks/BaseBossAttack.cs
- Assets/GameAssets/Boss/BossScripts/Attacks/BossAttackActSystem.cs
- Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackController.cs
- Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackEnemyController.cs
- Assets/GameAssets/Boss/BossScripts/Attacks/Vine/VineAttackController.cs
- Assets/GameAssets/World/WorldPrefabs/FerryBoat.prefab
- Assets/GameAssets/World/WorldPrefabs/Interactables/Generator.prefab
- Assets/GameAssets/World/WorldPrefabs/Interactables/Generator.prefab.meta
- Assets/GameAssets/World/WorldScripts/Interactables/Specific Interactables/GeneratorInteractable.cs
- Assets/GameAssets/World/WorldScripts/Interactables/Specific Interactables/GeneratorInteractable.cs.meta
- Assets/General/Prefabs/Managers/GameplayManagers/GameplayManagers.prefab
- Assets/General/Scenes/GeneralTestGyms/Generator.unity.meta
- Assets/General/Scripts/Story/StoryManager.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-520
Tbh the generator functionality ended up being a small part of this PR. Had to make adjustments to how attacks work to forcibly end certain attacks. The words from the task of "ends all current attacks and progress to the next story beat." Takes up a decent chunk of this entire PR. Also had to hook up the Story Manager to the game and have it spawn enemies on the correct act.
How to test
-Go to the main scene. I added an option to progress to the next beat on pressing 'U' Once you are on the third beat (When the debug displays 2, because it starts at 0) You can interact with the generator. This will progress to the next beat and spawn the lockdown …
> Vs-eng-generator-interactable-lv-520

- Assets/General/Scenes/BuildScenes/CreditsScreen.unity
- Assets/General/Scenes/BuildScenes/CreditsScreen.unity.meta
- Assets/General/Scripts/MenuFunctionality/CreditsScrolling.cs
- Assets/General/Scripts/MenuFunctionality/CreditsScrolling.cs.meta
Created a new scene with a modified version of the title screen scrolling script. Barebones framework for credits scrolling.
Jira Task: https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32?selectedIssue=LV-458
Documentation :https://docs.google.com/document/d/1wE085LI0ENuc6cwNnggMidBO4bbdRPtDtKtwPnB4IhU/edit?tab=t.0
This functionality can be tested in the CreditsScreen scene by adjusting the Credits Scrolling script hosted by the MovingUI GameObject.
> vs-eng-credits-functionality-lv-458

- Assets/GameAssets/World/WorldPrefabs/FerryBoat.prefab
Rescaled all the parent objects so now everything should be operating on the same scaling stuff
> Vs des boatscalingfix

- Assets/GameAssets/Player/PlayerPrefabs/Harpoon.prefab
- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonGun.cs
- Assets/GameAssets/Player/PlayerScripts/PlayerReticle.cs
Jira: https://bradleycapstone.atlassian.net/browse/LV-476?atlOrigin=eyJpIjoiOGNhY2NhOTVlODg0NDc3NjhkM2I5YjM3NDQ2ZTNhZTgiLCJwIjoiaiJ9
no change in documentation since it is all engineer side
to test, hold and release t to focus and unfocus
scripts changed: PlayerReticle and HarpoonGun
> Vs eng clean up reticle code lv 476

- Assets/GameAssets/Player/PlayerPrefabs/PlayerKit.prefab
- Assets/GameAssets/Player/PlayerScripts/PlayerInteraction.cs
- Assets/GameAssets/UI/UIScripts.meta
- Assets/GameAssets/UI/UIScripts/InteractableUI.cs
- Assets/GameAssets/UI/UIScripts/InteractableUI.cs.meta
- Assets/General/Prefabs/DesignPlayerPackage.prefab
Moves UI functionality to its own script and subsequently cleaned up the prior functionality for interaction system
> Vs eng isolate interaction UI code lv 559

- Assets/GameAssets/Boss/BossPrefabs/WeakPoints/WeakPoint.prefab
- Assets/GameAssets/Player/PlayerPrefabs/HarpoonProjectile.prefab
- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonProjectileMovement.cs
jira: https://bradleycapstone.atlassian.net/browse/LV-486?atlOrigin=eyJpIjoiOWExMDdkZGY1ZDJkNDc2MGIzODMyOGNjZDVjNDVmYjMiLCJwIjoiaiJ9
how to test: 
go into main scene, fire, see that it doesn't go through walls anymore : )
> Vs eng harpoon can shoot through every wall of the ship lv 478

- Assets/GameAssets/Player/PlayerScripts/PlayerHealth.cs
- Assets/General/Scripts/Console/ConsoleController.cs
Jira Link - https://bradleycapstone.atlassian.net/browse/LV-558
Description - should take damage is hidden in inspector now
Best tested by looking at the player prefab to see if the variable is visible on the player health script
> Vs-Des-HideInInspector-LV-558

- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonDamage.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-582
Fixed the issue of the harpoon not dealing damage. (I removed a single line)
While working on this I found another error regarding FMOD that can be found here 
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?selectedIssue=LV-613
> vs-eng-beat-4-attack-bug

- Assets/GameAssets/Boss/BossPrefabs/Attacks/LockdownAttack/PatrolEnemy.prefab
- Assets/GameAssets/Boss/BossScripts/Attacks/BaseBossDamage.cs
- Assets/GameAssets/Boss/BossScripts/Attacks/BaseBossDamage.cs.meta
- Assets/General/Scripts/Damage/BaseDamage.cs
The lockdown enemy no longer pushes the player. Also I made it deal damage on stay because it felt odd that it would collide with you and then it wouldn't hurt you until you moved away
> vs-eng-Seeking-attack-pushes-player-through-walls-LV-526

- Assets/General/Scenes/BuildScenes/Submenus/SettingsMenuScene.unity
Changed the sizes of some text boxes and fixed a typo: "Sensativity" to "Sensitivity".
Jira Issue: https://bradleycapstone.atlassian.net/browse/LV-451
Changes observable in the Controls submenu scene.
> vs-ux-pause-menu-adjustments

- Assets/General/Prefabs/PlayerHUDCanvas.prefab
Jira: https://bradleycapstone.atlassian.net/browse/LV-635?atlOrigin=eyJpIjoiN2Y0MzJmOWE1ZjU4NDM1NWJkMTFiYmU0MWVmMTkwOTUiLCJwIjoiaiJ9
Moved the dialogue text and interaction text.
> VS-UX-LV-635-Dialogue-Text-Alter

- Assets/GameAssets/Player/PlayerPrefabs/PlayerKit.prefab
- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonGun.cs
- Assets/GameAssets/Player/PlayerScripts/PlayerMovementController.cs
Changes:
- Edited values of Cinemachine camera
- Decoupled camera and player so cinemachine's targeting isn't fighting the object's parenting
- Disabled gravity in player Rigidbody and added a manual downward velocity in the movement routine
- Increased gravity
- Added a check for if the player is grounded + not moving to prevent sliding off objects like stairs
- Added a ramp collider for the stairs
> vs-bug-fix-player-controller

- Assets/General/Scripts/ScreenText/DialoguePopUps.cs
- Added a function to prevent the dialogue from ever overlaying
- This function is public so it should be able to get called at any time
> Vs eng timed dialogue bug lv 650

- Assets/GameAssets/Player/Input/PlayerInputMap.cs
- Assets/GameAssets/Player/Input/PlayerInputMap.inputactions
Numpad enter added to getting into game
> Numpad enter added

- Assets/GameAssets/Player/PlayerAnimations/Harpoon/Holster.anim
- Assets/GameAssets/Player/PlayerAnimations/Harpoon/Reload.anim
- Assets/GameAssets/Player/PlayerAnimations/Harpoon/Unholster.anim
- Assets/GameAssets/Player/PlayerPrefabs/Harpoon.prefab
- Assets/GameAssets/World/WorldPrefabs/PlayerInteractables/AmmoRack.prefab
https://bradleycapstone.atlassian.net/browse/LV-640
https://bradleycapstone.atlassian.net/browse/LV-646
https://bradleycapstone.atlassian.net/browse/LV-658
https://bradleycapstone.atlassian.net/browse/LV-656
-Fixed the holster animation
-Made the reload time match with the animation, so you cannot shoot while still reloading
-Adjusted harpoon and health prefabs in the flipped version
-Adjusted the collider for the Harpoons Racks so you cannot get ammo through the wall
> vs-des-Gabe'sFixes

- Assets/General/Audio/FMODScripts/FmodSfxEvents.cs
- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
- Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/RuntimeSfxManager.cs
- Added a short delay before the first footstep sfx plays
- slowed the footstep speed
> Footstep adjustments

- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonGun.cs
- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonProjectileMovement.cs
- Assets/GameAssets/World/WorldPrefabs/PlayerInteractables/Hatch.prefab
- Assets/GameAssets/World/WorldPrefabs/PlayerInteractables/Hatch.prefab.meta
- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/SceneLoadingManager.prefab
- Assets/General/Scenes/BuildScenes/MazeScene.unity
- Assets/General/Scenes/BuildScenes/MazeScene.unity.meta
- Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/AframaxSceneManager.cs
- Assets/General/Scripts/ScreenText/TutorialPopUps.cs
- Assets/General/Scripts/Story/HatchSceneTransition.cs
- Assets/General/Scripts/Story/HatchSceneTransition.cs.meta
- ProjectSettings/EditorBuildSettings.asset
- There is a white block at the front of the boat that can be interacted with
- It will change scenes to the maze scene
The maze scene is currently just a void, I was focusing on functionality
> Alpha eng below deck

- Assets/GameAssets/Player/PlayerScripts/PlayerHealthUI.cs
- Assets/General/Prefabs/PlayerHUDCanvas.prefab
The fade in, how long it's on screen, and fade out are all customizable by design
> Implement UI heart fading

- Assets/General/Prefabs/Tutorials/TutorialWalkObject.prefab
- Assets/General/Prefabs/Tutorials/TutorialWalkObject.prefab.meta
- Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
Hopefully fixed end of game thing
> Readded Walk into this block for end of game

- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/green_heart_lrg.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/green_heart_med.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/green_heart_sml.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/orange_heart_lrg.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/orange_heart_med.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/orange_heart_sml.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/red_heart_lrg.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/red_heart_med.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/red_heart_sml.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/yellow_heart_lrg.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/yellow_heart_med.png.meta
- Assets/GameAssets/UI/UIAnimations/Health/Heart/Old_Heart_Assests/yellow_heart_sml.png.meta
- Assets/GameAssets/World/WorldPrefabs/HorrorMoments.meta
- Assets/GameAssets/World/WorldPrefabs/HorrorMoments/SoundHorrorMoment.prefab
- Assets/GameAssets/World/WorldPrefabs/HorrorMoments/SoundHorrorMoment.prefab.meta
- Assets/General/Scripts/HorrorMoments.meta
- Assets/General/Scripts/HorrorMoments/SoundHorrorMoment.cs
- Assets/General/Scripts/HorrorMoments/SoundHorrorMoment.cs.meta
Jira link - https://bradleycapstone.atlassian.net/browse/LV-835
Documentation: https://docs.google.com/document/d/1vyBmTA5qLdMa2GQAtw6hPnNssgZg8C5hR3PMd1Bs3zY/edit?usp=sharing
a prefab that plays a horror moment sound like the thump of the night on the trigger with it.
> Alpha-ThumpInTheNightHorrorMoment-LV-835

- Assets/GameAssets/Player/PlayerScripts/PlayerCameraController.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-861
While trying to fix the issue of the gravity increasing while pausing I found it was fixed and discovered a separate issue. The camera sway from walking would duplicate.
> alpha-eng-DuplicatedCameraSway-LV-861

- Assets/GameAssets/World/WorldPrefabs/HallwayToolkit/BasicRoom.prefab
- Assets/GameAssets/World/WorldPrefabs/Interactables/GasCanInteractable.prefab
- Assets/GameAssets/World/WorldPrefabs/Interactables/GasCanInteractable.prefab.meta
- Assets/GameAssets/World/WorldPrefabs/Interactables/Generator.prefab
- Assets/GameAssets/World/WorldPrefabs/Interactables/Keynteractable.prefab
- Assets/GameAssets/World/WorldPrefabs/Interactables/Keynteractable.prefab.meta
made basic prefabs for the other interactables needed for the mazes progression inside of the mazes
> Alpha des alpha interactables

- Assets/GameAssets/Player/PlayerPrefabs/Harpoon.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/KeyMaze.prefab
> Alpha des monsterimplementation

- Assets/General/Prefabs/Tools/StoryBeatProgressionTrigger.prefab
- Assets/General/Prefabs/Tools/StoryBeatProgressionTrigger.prefab.meta
- Assets/General/Scripts/Story/StoryProgressionTrigger.cs
- Assets/General/Scripts/Story/StoryProgressionTrigger.cs.meta
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-843
A second short PR. Just adds a script to progress the story beat on contact. There is also a prefab for design to use as they need it.
> alpha-eng-Develop-Chase-Sequence-Functionality-needed-by-programming-LV-843

- Assets/GameAssets/World/WorldPrefabs/LevelInteractables.meta
- Assets/GameAssets/World/WorldPrefabs/LevelInteractables/LightInteractable.prefab
- Assets/GameAssets/World/WorldPrefabs/LevelInteractables/LightInteractable.prefab.meta
- Assets/GameAssets/World/WorldScripts/Interactables/LightInteractable.cs
- Assets/GameAssets/World/WorldScripts/Interactables/LightInteractable.cs.meta
- Assets/General/Scenes/GeneralTestGyms/LevelInteractions.unity.meta
Go into the ```General>Scenes>GeneralTestGyms``` and select the LevelInteractions scene.
At the back of the boat is a white block that can turn on a light (the side without the generator).
It will flicker, it can be clicked again to turn off the light. The light will automatically turn off after a variable amount of time.
> Alpha-Eng-Light-Interactable-LV

- Assets/GameAssets/Player/PlayerPrefabs/PlayerSpawnPoint.prefab
- Assets/GameAssets/Player/PlayerScripts/PlayerFunctionalityCore.cs
- Assets/GameAssets/Player/PlayerScripts/PlayerMovementController.cs
- Assets/GameAssets/Player/PlayerScripts/PlayerSpawnPoint.cs
- Assets/General/Prefabs/DesignPlayerPackage.prefab
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-844
Adds the ability on the player spawn point to spawn without movement input. This was requested by design for the end sequence.
> alpha-eng-Develop-Ending-Functionality-need-by-programming-LV-844

- Assets/GameAssets/World/WorldArt/MazeTextures/ImportantRoom.mat
- Assets/GameAssets/World/WorldArt/MazeTextures/ImportantRoom.mat.meta
- Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
Updated the mazes in scene to fix some textures so Peyton doesnt have to reload stuff atm
> Updated in scene textures to fix em

- Assets/GameAssets/World/WorldScripts/HorrorMoments/PottyBreak.cs
whoops as it turns out i forgot something lol. Added jumpscare. Literally 1 line of code.
> alpha-eng-Develop-Potty-Break-LV-842

- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
- Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
This is John using Marissa's computer asking to look to see that the audio manager's children have all but the radio sfx in the sfx child. The atmosphere child should have no more audio for it.
> Added in sound effects - John

- Assets/GameAssets/World/WorldPrefabs/HorrorMoments/LightFlickerer.prefab
- Assets/GameAssets/World/WorldPrefabs/HorrorMoments/LightShifter.prefab
- Assets/GameAssets/World/WorldPrefabs/HorrorMoments/SoundHorrorMoment.prefab
- Assets/GameAssets/World/WorldPrefabs/HorrorMoments/TentacleMover.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/KeyMaze.prefab
- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
Added some sounds, changes footstep repeat length so not so much, Tried adding Potty Break (bugged currently)
https://bradleycapstone.atlassian.net/browse/LV-777
https://bradleycapstone.atlassian.net/browse/LV-838
To see them, play through the maze and you should see:
1. Light Change with sound
2. Thump with slither
3. Tentacle Slither Away down the hall with flickering light sounds and slither sound
Also footsteps aren't as frequent
> alpha-des-HorrorMomentsTheFinale

- Assets/General/Prefabs/Tools/Console.prefab
- Assets/General/Prefabs/Tools/Dev_Console_Canvas.prefab
- Assets/General/Prefabs/Tools/Dev_Console_Canvas.prefab.meta
Jira Link: https://bradleycapstone.atlassian.net/browse/LV-940
Description: Added the scene transition button back into the dev-console
Best tested: check if the scene transition button is in the dev console and if the buttons work in the game scene. You may need to exit the dev console for the scene transition to work
> Alpha-Scene-Transition-Buttons-LV-940

- Assets/General/Prefabs/DesignPlayerPackage.prefab
Jira Link: https://bradleycapstone.atlassian.net/browse/LV-951
Description: The dev console is now part of the player package. It can be opened wherever the player is. As Ryan said, killing two birds with one stone
This is the other task that it fixes: https://bradleycapstone.atlassian.net/browse/LV-884
> Alpha-Missing-Prefab-In-The-Maze-Scene-Rework-LV-951

- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
- Assets/General/Scenes/BuildScenes/TitleScreen.unity
Jura task:https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32?assignee=63c32962c52a63dcda83f747&selectedIssue=LV-953 
The SFX should likely not loop after opening the menu and then closing it
> Switched the sfx to a different one that would not loop (Hopefully)

- Assets/GameAssets/Player/PlayerAnimations/Harpoon/Reload.anim
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-986
Literally just an animation fix. No code involved. On development the harpoon doesn't reappear in the reload animation until the animation completes. I fixed it so the harpoon appears when the gun is cocked back.
In engine review estimation: <1-2 minutes
> beta-eng-Reload-animation-not-spawning-in-the-harpoon-LV-986

- Assets/GameAssets/World/WorldPrefabs/Environment Chunk/Enviornmental Chunk 2-XL Variant.prefab
- Assets/General/Art/ArtTestGyms/ArtTesting.unity
- Assets/General/Models/MangroveTree.meta
- Assets/General/Models/MangroveTree/Bark_Color.png
- Assets/General/Models/MangroveTree/Bark_Color.png.meta
- Assets/General/Models/MangroveTree/Bark_Normal.png
- Assets/General/Models/MangroveTree/Bark_Normal.png.meta
- Assets/General/Models/MangroveTree/MangroveLeaves.mat
- Assets/General/Models/MangroveTree/MangroveLeaves.mat.meta
- Assets/General/Models/MangroveTree/MangroveTreeBark.mat
- Assets/General/Models/MangroveTree/MangroveTreeBark.mat.meta
- Assets/General/Models/MangroveTree/MangroveTree_01.fbx
- Assets/General/Models/MangroveTree/MangroveTree_01.fbx.meta
- Assets/General/Models/MangroveTree/MangroveTree_02.fbx
- Assets/General/Models/MangroveTree/MangroveTree_02.fbx.meta
- Assets/General/Models/MangroveTree/MangroveTree_03.fbx
- Assets/General/Models/MangroveTree/MangroveTree_03.fbx.meta
- Assets/General/Models/MangroveTree/MangroveTree_Color.png
- Assets/General/Models/MangroveTree/MangroveTree_Color.png.meta
- Assets/General/Models/MangroveTree/MangroveTree_Sway.png
- Assets/General/Models/MangroveTree/MangroveTree_Sway.png.meta
- Assets/General/Shaders.meta
- Assets/General/Shaders/Foliage.meta
- Assets/General/Shaders/Foliage/StylizedLeaf.shadergraph
- Assets/General/Shaders/Foliage/StylizedLeaf.shadergraph.meta
Implementation of 3 variants of the mangrove tree in our main scene. Also made a generic foliage shader for SpeedTree assets. ([Jira task](https://bradleycapstone.atlassian.net/browse/LV-1057))
How to test
- Go to GameScene
- Enjoy your twig
> beta-art-mangrove-tree-lv-1057

- Assets/GameAssets/Boss/BossMats/Monster Blood Color Test.mat
- Assets/GameAssets/Boss/BossMats/Monster Blood.mat
- Assets/GameAssets/World/WorldArt/MazeTextures/ImportantRoom.mat
- Assets/GameAssets/World/WorldArt/MazeTextures/MazeMetal.mat
- Assets/GameAssets/World/WorldArt/MazeTextures/MazeMetal2.mat
- Assets/GameAssets/World/WorldArt/WorldShaders/CelShader/CelShaderStandard.shadergraph
- Assets/GameAssets/World/WorldMaterials/AltMaze.mat
- Assets/GameAssets/World/WorldPrefabs/Mazes/KeyMaze(Easier).prefab
Fixed the rendering issues playtesters noticed in the MazeScene ([Jira task](https://bradleycapstone.atlassian.net/browse/LV-1055))
> beta-art-updating-materials-lv-1055

- Assets/GameAssets/Boss/BossPrefabs/GroupOfVines.prefab
- Assets/GameAssets/Boss/BossScripts/Attacks/ProceduralAttack/ChaseSequenceVine.cs
- Assets/GameAssets/Boss/BossScripts/Attacks/ProceduralAttack/ChaseVineGroup.cs
- Assets/GameAssets/Boss/BossScripts/Attacks/ProceduralAttack/ProceduralVine.cs
- Assets/General/Audio/FMODScripts/FmodSfxEvents.cs
- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
- Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-1160
The monster during the chase sequence can play 2 sounds. The task technically only asked for one, but the task can be quiet. I made it so there is a start up audio for the chase sequence as well as a looping audio of the monster.
Best tested by going into Tommy's procedural test scene and getting chased. Obviously the audio being used is temporary and just for testing. (It plays generator sounds)
Code Review Estimation: <6 minutes
In Engine Review Estimation: <3 minutes
> beta-eng-Chase-Monster-Sound-effect-Engineering-LV-1160

- Assets/GameAssets/World/WorldPrefabs/Crate Pile.prefab
- Assets/GameAssets/World/WorldPrefabs/Crate Pile.prefab.meta
- Assets/GameAssets/World/WorldPrefabs/Mazes/ThirdMazeBackTrack.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/ThirdMazeBackTrack.prefab.meta
Made Peyton's crate wall a prefab
Used the crate walls to create a single path back through maze three once you pick up the gascan
Added it to the story manager
> LV-1188-Streamlining-Maze-3-Runback

- Assets/GameAssets/Player/PlayerPrefabs/HarpoonProjectile.prefab
- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonProjectileMovement.cs
- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonProjectileVisualAudioEffects.cs
- Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonVisualAudioEffectsBank.cs
- Assets/GameAssets/World/WorldScripts/Boat/BoatGeometryHealth.cs
- Assets/General/Audio/FMODScripts/FmodSfxEvents.cs
- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/VfxManager.prefab
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-1136
Harpoon plays audio on contact with surfaces. Built on top of the VFX system for harpoon collisions.
How to test: Go into the boat scene. If you shoot the floor you hear a loud thud, If you shoot the metal rim, you hear a quieter but notable thud. These are purely test audio.
Code Review Estimation: <5 minutes
In Engine Review Estimation: <3 minutes
> beta-eng-Additional-Harpoon-Impact-SFX-Functionality-LV-1136

- Assets/GameAssets/Player/PlayerScripts/PlayerCameraController.cs
Wahoo the weapon recenters from walking sway when you start focusing! Test in any scene
Jira Task: https://bradleycapstone.atlassian.net/browse/LV-1232?atlOrigin=eyJpIjoiNzgyMmNmYmE4NjczNGY1MmJkYTk3YzllOWIyNDYxNjEiLCJwIjoiaiJ9
Code Review Time: <2 minutes
In-Engine Review Time: <3 minutes
> beta-eng-Weapon-being-off-center-at-times-LV-1232

- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaChaseBuildUp.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaChaseBuildUp.prefab.meta
Made the transition area between maze and chase
> made new prechase prefab based on Caden sketch

- Assets/GameAssets/Boss/BossPrefabs/Stem(jiffy lube guy).prefab
- Assets/GameAssets/World/WorldScripts/HorrorMoments/SlytherinTentacleMove.anim
- Assets/General/Prefabs/Horror Moments.prefab
- Assets/General/Prefabs/Horror Moments.prefab.meta
- Assets/General/Scenes/GreyBoxing/HorrorMomentsGreybox.unity.meta
I have created a prefab called "Horror Moments" that has:
- Light Shift
- Slytherin
- Thump
Go to **HorrorMomentsGreyBox** scene to check my work
It should fit perfectly in the Weird Maze, I setup the prefab so it aligns at 0,0,0 transform (assuming the maze doesn't move).
Jira Task: 
https://bradleycapstone.atlassian.net/browse/LV-1341?atlOrigin=eyJpIjoiM2Q3ZDEyYjQ0M2NhNDVkYWFjZmYzY2RiNjA3M2MxYzYiLCJwIjoiaiJ9
> Beta des horror moments level pass lv 1341

- Assets/GameAssets/World/WorldTestGyms/PostProcessingTestGym/GlobalVolumeAboveDeck Profile.asset
- Assets/General/Prefabs/DesignPlayerPackage.prefab
Added Post Processing to the PlayerPackage
https://bradleycapstone.atlassian.net/browse/LV-1274
You should be able to just see it in scene view and when playing. If you want to compare, just go into the PlayerKit -> Main Camera -> and turn off and on postprocessing under Render Settings
> beta-des-Add-Post-Processing-To-Levels-LV-1274

- Assets/FunctionalTeams/Narrative/Prefabs/MonsterAttacks.prefab
- Assets/FunctionalTeams/Narrative/Prefabs/MonsterAttacks.prefab.meta
- Assets/GameAssets/Boss/BossPrefabs/Stem(attack).prefab
Monster attacks are set up in a prefab in Narrative folder under prefabs, theres a line up cube for the water anomliy that you can use to get the monsters attacks set up in maze.
> Monster Level Pass LV-1343

- Assets/GameAssets/World/WorldArt/Models/Soundtube/Files/soundtubev2_SmallTube1_AlbedoTransparency.png
- Assets/GameAssets/World/WorldArt/Models/Soundtube/Files/soundtubev2_SmallTube1_MetallicSmoothness.png
- Assets/GameAssets/World/WorldArt/Models/Soundtube/Files/soundtubev2_SmallTube2_AlbedoTransparency.png
- Assets/GameAssets/World/WorldArt/Models/Soundtube/Files/soundtubev2_SmallTube2_MetallicSmoothness.png
Just some extra shading done in the outside tubes!
> Updated Sound Tube Prefab MAT

- Assets/GameAssets/World/WorldArt/Models/Soundtube/SoundtubePrefab.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaNormalZone.prefab
- Assets/General/Scenes/BuildScenes/MazeScene.unity
Fixed some holes in the ceiling
Added box colliders to some props to prevent surfing
Moved soundtube into actual playspace prefab
added collider to soundtube
> Beta des normal level collision check lv 1259

- Assets/General/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
- Assets/General/Scenes/BuildScenes/MazeScene.unity
Added in the warp sound effect when changing scenes, you should be able to hear it after picking up the spanner and using it on the generator in the maze scene
Jura task: https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=63c32962c52a63dcda83f747&selectedIssue=LV-1278
> Beta des healing ammo warp sfx implementation lv 1278

- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaChaseBuildUp.prefab
- Assets/General/Scenes/BuildScenes/MazeScene.unity
Added in Miles's pass
Added some box colliders to prevent surfing 
Closed some ceiling holes
Added some lighting
> Lv 1355 chase build up collision check

- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaChaseSequence.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaMaze.prefab
Added Miles's Stuff
Added anti surf colliders
Added The Collider
Patched ceilings holes
> Beta des chase level collision check lv 1261

- Assets/General/Scenes/BuildScenes/MazeScene.unity
- After the player grabs the spanner the voice tube is duplicated and clips into itself (fixed)
> beta-des-Voice-Tube-Duplication-LV-1429

- Assets/GameAssets/World/WorldPrefabs/PlayerInteractables/HealthPack.prefab
- Adjusted health pack prefab so its transformation is no longer stretched
> beta-des-Stretched-Health-Pack-LV-1430

- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaNormalZone.prefab
- Added 63 more props to the normal level prefab to make it feel more cluttered
> beta-des-2nd-Prop-Pass-for-Normal-Level-LV-1444

- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaChaseBuildUp.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaMaze.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaNormalZone.prefab
Added ceiling colliders to
Normal Zone
Maze
Chase Buildup
> added ceiling colliders to help with collision issues

- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaChaseBuildUp.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaMaze.prefab
- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/BetaNormalZone.prefab
- Assets/General/Scenes/BuildScenes/MazeScene.unity
Objective updates for the player as they get through the game. THE PAUSE MENU DOES NOT UPDATE. lmk if you think the objectives should say different things or if they are timed poorly.
> "Fixing the Generator" Objective LV 1448

- Assets/GameAssets/Player/PlayerScripts/PlayerHealthUI.cs
https://bradleycapstone.atlassian.net/browse/LV-1026?atlOrigin=eyJpIjoiM2MzMWJlY2JhYzVhNDViZjhlOWZlZmJhZGJlOTBiZWEiLCJwIjoiaiJ9
Changed the heart visibility coroutine so that it takes into account the current visibility
> beta eng Heart Animation Bug Repeated fade ins and outs LV 1026

- Assets/GameAssets/World/WorldScripts/Interactables/NoteInteractable.cs
- Assets/General/Scripts/MenuFunctionality/TutorialPopUp.cs
- The tutorial will no longer prevent the mouse from being seen across UI screens
Fixed the tutorial bug I also brought the note interactable to parity and fixed errors from popping up from that script
> Pause-death-bug-is-back-LV-1467

- Assets/General/Scenes/BuildScenes/MazeScene.unity
Removed the pop up from the generator whenever you cannot interact with it.
> Pop up over Generators LV 1458

- Assets/General/Scripts/MenuFunctionality/PauseMenu.cs
https://bradleycapstone.atlassian.net/browse/LV-1421?atlOrigin=eyJpIjoiNTdkNjRhNWI2M2JmNGFiNGI5NWU2MTgxYzViM2I1ZDgiLCJwIjoiaiJ9
Made the audio mute on pause, essentially a poor man's pause audio function
> Beta eng paused audio lv 1421

- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/ActualMazes/BetaNormalZone.prefab
I added in the doors for the 4th time! Just the ones in the beginning scene though
> Beta des doors again

- Assets/GameAssets/Boss/BossPrefabs/Stem(attack).prefab
- Assets/GameAssets/Boss/BossScripts/Attacks/ProceduralAttack/ProceduralVine.cs
- Assets/GameAssets/Player/PlayerScripts/PlayerCameraController.cs
- Assets/GameAssets/World/WorldPrefabs/LV Wall Decal Hole v3.prefab
- Assets/GameAssets/World/WorldPrefabs/LV Wall Decal Hole v3.prefab.meta
- Assets/GameAssets/World/WorldPrefabs/Mazes/Beta/ActualMazes/BetaMaze.prefab
- Assets/SaveData/Data.json
Dropped the appearance speed for tentacles slightly
Moved triggers around to try and make monsters work a bit better
> Beta des avoiding monsters is too easy lv 1379

- Assets/General/Scripts/Managers/AbstractManagers/CinematicManager.cs
- ProjectSettings/AudioManager.asset
https://bradleycapstone.atlassian.net/browse/LV-1476?atlOrigin=eyJpIjoiZWU0MzVjMjhmZjZhNDUzM2FlZGM1YzU4NzRiOGZlMTAiLCJwIjoiaiJ9
Fixed the audio so that now it actually stops during the cutscenes, and doesn't carry it over to the title screen
> beta eng Add Audio to Cinematics LV 1476

- Assets/GameAssets/World/WorldArt/Models/BoatShaderTest/BoatTestWater.mat
- Assets/GameAssets/World/WorldArt/WorldShaders/Water/WaterInterior.mat
- Assets/GameAssets/World/WorldArt/WorldShaders/Water/WaterInterior.mat.meta
- Assets/General/Materials/Wood/WoodMazePlanks.mat
- Assets/General/Materials/Wood/WoodMazePlanks.mat.meta
- Assets/General/Scenes/BuildScenes/MazeSubScenes/AdditiveMaze02.unity
Band-aid water fix for beta build
> beta-fix-water-area-lv-1484

- .github/workflows/devbuild.yml
Changed runs-on parameter from latest-ubuntu to self-hosted, so that it does not try and run using the cloud instances
> Update devbuild.yml to run on self-hosted

- Assets/Scripts/Managers/UniversalManagers/MainUniversalManagers/SaveManager.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-1702
There was an error with the save data. If you play the gold branch from the main menu the game will throw an error about not finding a path. If you play from the main menu in this branch that will not happen. The file path of the save data was modified, but the code was not updated to be aware of this.
Code Review Estimation: <1 minute
In Engine Review Estimation: <4 minutes to check both gold and this branch
> gold-eng-Fix-JSON-Error-LV-1702

- Assets/Art/Animations/WorldAnimations/LightLanternFlicker.controller
- Assets/Art/VFX/WorldEffects/LightLanternOrange.prefab
- Assets/Art/VFX/WorldEffects/LightLanternOrangeFlicker.prefab
- Assets/Scripts/Story/RandomizedAnimation.cs
- Assets/Scripts/WorldScripts/HorrorMoments/LightController.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-1719
This shouldn't actually feel different from main at all. I reworked the way the light flicker functions from being on an animation to being done through script. The reason is that you can modify the intensity of the light and the flicker will scale based on that. (It doesn't update at runtime. It sets its starting intensity to scale off of in start)
Honestly making the animation curves match was what took the longest.
Feel free to modify the intensity of a light in maze 2 then try playing the game (from the maze scene) and that lights flicker will scale properly.
Code Review Estimation: <5 minutes
In Engine Review Estimation: <6 minutes
> gold-eng-Normalized-Flicker-Animations-LV-1719

- Assets/Scripts/Managers/UniversalManagers/MainUniversalManagers/AframaxSceneManager.cs
- Assets/Scripts/Managers/UniversalManagers/MainUniversalManagers/RuntimeSfxManager.cs
- Assets/Scripts/PlayerScripts/PlayerHealth.cs
Jira Link: https://bradleycapstone.atlassian.net/browse/LV-1712
Description: When you die, you can still hear the walking footsteps. had trouble replicating the bug perfectly, but I put in a fix, and there don't seem to be foot step sounds when I die. 
Best Tested: Play the game and try to die. If there is no footsteps, then it works
> gold-eng-Walking-Audio-DeathBug-LV-1712

- Assets/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
- Assets/Prefabs/StoryBeatAudioManager.prefab
- Assets/Prefabs/StoryBeatAudioManager.prefab.meta
- Assets/Scenes/BuildScenes/MazeScene.unity
StoryManager seemed to have an issue with the StoryBeatAudioManager so Warp and other sounds were not playing. I made the StoryBeatAudioManager it's own prefab and had to drag the sounds to the scenes StoryManager.
https://bradleycapstone.atlassian.net/browse/LV-1569
Just give it a quick play and make sure the warp and a few other sounds like generator fail play upon beat changes (interacting with generator)
> gold-des-Implement-Warp-Sound-LV-1569

- Assets/Art/Animations/PlayerAnimations/Harpoon/Recoil.anim
Recoil Harpoon Gun Animation was clipping into camera, fixed
https://bradleycapstone.atlassian.net/browse/LV-1561
Just shoot and make sure it doesn't clip
> gold-des-Adjust-Harpoon-Clipping-into-Camera-LV-1561

- Assets/Scripts/Maze/GeneralPlayerCollisionTrigger.cs
- Assets/Scripts/Maze/GeneralPlayerCollisionTrigger.cs.meta
- Assets/Scripts/PlayerScripts/PlayerCollision.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-1754
Bonus task requested by Oliver. Just a trigger with a unity event for design to do whatever the heck they want with.
You can drag it into a maze scene and play with it to have it do whatever
Code Review Estimation: <2 minutes
In Engine Review Estimation: <5 minutes
> gold-eng-wall-trigger-LV-1754

- Assets/Art/TechArt/Shaders/Datamoshing/DatamoshingEffect.shadergraph
- Assets/Scripts/ThirdParty.meta
- Assets/Scripts/ThirdParty/URPGrabPass.meta
- Assets/Scripts/ThirdParty/URPGrabPass/GrabColorTexturePass.cs
- Assets/Scripts/ThirdParty/URPGrabPass/GrabColorTexturePass.cs.meta
- Assets/Scripts/ThirdParty/URPGrabPass/GrabPassRendererFeature.cs
- Assets/Scripts/ThirdParty/URPGrabPass/GrabPassRendererFeature.cs.meta
- Assets/Scripts/ThirdParty/URPGrabPass/GrabTiming.cs
- Assets/Scripts/ThirdParty/URPGrabPass/GrabTiming.cs.meta
- Assets/Scripts/ThirdParty/URPGrabPass/URPGrabPass.asmdef
- Assets/Scripts/ThirdParty/URPGrabPass/URPGrabPass.asmdef.meta
- Assets/Scripts/ThirdParty/URPGrabPass/UseColorTexturePass.cs
- Assets/Scripts/ThirdParty/URPGrabPass/UseColorTexturePass.cs.meta
- Packages/manifest.json
- Packages/packages-lock.json
Included URPGrabPass as a C# assembly and not a Unity package to fix issues with Unity needing to pull the package from Git.
> gold-art-fix-editor-bug-lv-1956

- Assets/Prefabs/PlayerPrefabs/PlayerKit.prefab
- Assets/Prefabs/WorldPrefabs/PlayerInteractables/HealthPack.prefab
Bumped the monster damage down to 20 so now 1 health pack charge heals 1 monster hit
> Updated the monster to deal 20% damage

- Assets/Prefabs/CleosSoundTubes/CleosSoundTube.prefab
- Assets/Prefabs/CleosSoundTubes/TriggeredVA.prefab
- Assets/Prefabs/CleosSoundTubes/TriggeredVA.prefab.meta
- Assets/Prefabs/CleosSoundTubes/TriggeredVAChaseSequence.prefab
- Assets/Prefabs/CleosSoundTubes/TriggeredVAChaseSequence.prefab.meta
- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaChaseSequence.prefab
- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaMaze.prefab
- Assets/Resources/SaveData/Data.json
- Assets/Scenes/BuildScenes/MazeScene.unity
Refer to title, mostly.
What ISNT in yet:
A few banter lines, between the player and captain. This is because there's no way to space the triggers out in a way that would make the lines flow naturally. This can be solved by either: Making banter lines a triggered event directly in the story manager, or having both lines (Captain dialogue + Player response) recorded in the same sound clip, so that they can play in sequence without the need for 2 triggers.
> Added triggered dialogue VA

- Assets/Scripts/MenuFunctionality/TutorialPopUp.cs
Just added a simple bool and if statement so the tutorial door only opens once.
Jira Task: https://bradleycapstone.atlassian.net/browse/LV-1967?atlOrigin=eyJpIjoiYTNjZGM2ODAwMWVhNGQ5ODlhM2UwYmE3MzFjMWM2YTciLCJwIjoiaiJ9
> Door can now only be opened once

- Assets/Art/VFX/WorldEffects/VFXRainPatch.prefab
- Assets/Art/VFX/WorldEffects/VFXWaterDrip.prefab
- Assets/Prefabs/WorldPrefabs/Mazes/VariantForGold/BetaMaze (final harpoon and health locations).prefab.meta
- Assets/Scenes/TestGyms/ArtTestGyms/DecalMazeTesting.unity
Both the water drip and rain patch effects have been changed to the yellow color the team picked. You can go to DecalMazeTesting to see it on the rain, it's just easier because there's more droplets.
> Gold art water drip color change lv 1759

- Assets/Art/3D/Boss/BossPrefabs/Stem(attack).prefab
- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaMaze.prefab
Added back in old monsters for FUSE
(also fixed the eyeball hallway being broken)
> Lv 1974 put old monsters back into scene

- Assets/Art/VFX/WorldEffects/VFXWaterDrip.prefab
- Assets/Prefabs/Anomaly Prefabs/DatamoshTriggerZone.prefab
- Assets/Prefabs/Managers/UniversalManagers/MainUniversalManagers/AudioManager.prefab
- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaMaze.prefab
- Assets/Scenes/BuildScenes/DeathScreen.unity
- Assets/Scenes/BuildScenes/Submenus/CreditsScreen.unity
Added as much audio as I could, readded the water drips
https://bradleycapstone.atlassian.net/browse/LV-1976
Please get this in for FUSE
> gold-des-Implement-SFX-Pre-Fuse-LV-1976

- Assets/Prefabs/StoryBeatAudioManager.prefab
- Assets/Prefabs/StoryManager.prefab
- Assets/Prefabs/Tutorials/TutorialDoor.prefab
- Assets/Prefabs/Tutorials/TutorialNote.prefab
- Assets/Prefabs/WorldPrefabs/HorrorMoments/DoorLocked.prefab
- Assets/Prefabs/WorldPrefabs/HorrorMoments/DoorLocked.prefab.meta
- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaNormalZone.prefab
- Assets/Scenes/BuildScenes/MazeScene.unity
Implemented the door locked sfx and door open sfx.
I would recommend 2 attempts:
1. Run into the door to hear the locked sfx and interact with the note to hear the open sfx
2. Interact with the note first to hear the open sfx, then walk though the doorway to see if the locked door sfx triggers (it should NOT trigger)
Jira Task: https://bradleycapstone.atlassian.net/browse/LV-1805?atlOrigin=eyJpIjoiZjlhZWQ2ZTA3NmVlNGVlODgxN2MzZjE5ZDg5MzhkNTkiLCJwIjoiaiJ9
> Tutorial Door SFX Implemented

- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaChaseBuildUp.prefab
- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaMaze.prefab
- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaNormalZone.prefab
- implemented windows throughout the game
> gold-des-Implement-Window-Asset-LV-1830

- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaMaze.prefab
> fixed pipe

- Assets/Resources/SaveData/Data.json
- Assets/Scripts/WorldScripts/Interactables/NoteInteractable.cs
https://bradleycapstone.atlassian.net/browse/LV-1985
very simple bug fix, just disabling the note's ability to read inputs when you close it. tutorial notes don't have this issue
> Note Flipping SFX Bug-1985

- Assets/Scenes/BuildScenes/Submenus/SettingsMenuScene.unity
- Assets/Scenes/BuildScenes/TitleScreen.unity
- Assets/Scripts/Managers/UniversalManagers/MainUniversalManagers/SaveManagement/GameSaveData.cs
- Assets/Scripts/Managers/UniversalManagers/MainUniversalManagers/SaveManager.cs
- Assets/Scripts/Managers/UniversalManagers/MainUniversalManagers/UiManager.cs
- Assets/Scripts/MenuFunctionality/TitleScreenScrolling.cs
- Assets/Scripts/UI/GameplaySettings.cs
- Assets/Scripts/UI/VideoSettingsBehaviour.cs
- Assets/StreamingAssets/GameplaySettings.txt
[Jira Link](https://bradleycapstone.atlassian.net/browse/LV-1996)
The Controller UI swap got moved from Video to Gameplay
The setting now saves properly
The main menu now has text that changes because of this
This should take 5ish minutes non-code and another 5 for code
> Gold eng t itle screen controller swap UI lv 1996

- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaChaseSequence.prefab
moved start point for first chase sequence up more so player can't get behind it
> gold-des-Player-can-end-up-behind-the-monster-LV-2034

- Assets/Prefabs/WorldPrefabs/Scares.prefab
This is specifically for the second one way spawning with the barrel/golem split path
> moved second wall trigger to a spot that actually makes sense

- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaChaseBuildUp.prefab
- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaMaze.prefab
- Assets/Scenes/BuildScenes/MazeScene.unity
- check betamaze and betachasebuildup prefabs
> gold-des-Re-Implement-Weird-Save-Points-LV-2109

- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaNormalZone.prefab
Screenshot provided to show area
> GoldQa-Des-fixedzclippinginnormal

- Assets/Prefabs/WorldPrefabs/PlayerInteractables/AmmoRack.prefab
JiraLink: https://bradleycapstone.atlassian.net/browse/LV-2020
Description: The Ammo rack is counted as a harpoon. It doesn't anymore
> gold-eng-4-harpoons-from-refill-LV-2020

- Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaMaze.prefab
Moved 2nd note to be less missable
> GoldQA-Des-Moved2ndNote

- Assets/Art/3D/Environment/SeedPod/Files/NewTextures.meta
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodBase_AlbedoTransparency.png
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodBase_AlbedoTransparency.png.meta
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodBase_MetallicSmoothness.png
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodBase_MetallicSmoothness.png.meta
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodBase_Normal.png
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodBase_Normal.png.meta
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodHoles_AlbedoTransparency.png
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodHoles_AlbedoTransparency.png.meta
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodHoles_MetallicSmoothness.png
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodHoles_MetallicSmoothness.png.meta
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodHoles_Normal.png
- Assets/Art/3D/Environment/SeedPod/Files/NewTextures/Updated_seedpod_SeedPodHoles_Normal.png.meta
- Assets/Art/3D/Environment/SeedPod/Files/SeedPodBase.mat
- Assets/Art/3D/Environment/SeedPod/Files/SeedPodHoles.mat
Okay, so, I have made the seed pod textures much brighter than it was before, however in areas where the lighting is dim, it is still reading black. I checked all the other prefabs that were placed in the scene as well, they have all been updated with the new textures. Only caveat is that you can see the ones in better lit areas rather than the others. T^T
> LV-2141-Updated-SeedPod-Textures
