Last-Voyage/Aframax

Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackEnemyController.cs, Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackPatrolEnemyBehavior.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-636
Reason why is that the enemy was childed to the room, and so when the room was checking for if the player enetered the room it was taking into account both the room collider and the enemy collider. So it would increase the collision counter by 2 rather than 1. Had to make some minor adjustments to the enemy behavior to make that work. The enemy is now a child of the attack rather than the room
=> vs-eng-Procedural-tentacles-attach-to-player-LV-636

Assets/General/Prefabs/PlayerHUDCanvas.prefab
Jira: https://bradleycapstone.atlassian.net/browse/LV-649?atlOrigin=eyJpIjoiNDJkYmY0YzZiOTRhNDlhOGE4MGFhYjM3Yjk5OWE2ZDAiLCJwIjoiaiJ9
All I did was change the in-scene reticle scope opacity to match the unfocused reticle opacity. Fully seems to fix the issue. 
original bug was the reticle appearing as white at the start of the scene, and when restarting the game.
=> White Reticle: LV-649

Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackEnemyController.cs, Assets/GameAssets/Boss/BossScripts/Attacks/Lockdown/LockdownAttackPatrolEnemyBehavior.cs, Assets/GameAssets/Boss/BossScripts/WeakPoints/WeakPointHandler.cs, Assets/General/Scripts/Managers/UniversalManagers/MainUniversalManagers/RuntimeSfxManager.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-642
Fixed the issue with both attacks dying. The weak point handler destroyed its owner after all weak points are destroyed. It probably shouldn't have done that in the first place. That presented another issue. Fixed that one. Personally not a fan of the relationship the procedural animation object has to the rest of the attack, feels a little odd but I'm sticking with it
=> vs-eng-two-attacks-die-LV-642

Assets/GameAssets/Player/PlayerAnimations/Harpoon/Focus.anim, Assets/GameAssets/Player/PlayerAnimations/Harpoon/Holster.anim, Assets/GameAssets/Player/PlayerAnimations/Harpoon/Recoil.anim, Assets/GameAssets/Player/PlayerAnimations/Harpoon/Reload.anim, Assets/GameAssets/Player/PlayerAnimations/Harpoon/Unfocus.anim, Assets/GameAssets/Player/PlayerAnimations/Harpoon/Unholster.anim, Assets/GameAssets/Player/PlayerAnimations/Harpoon/harpoonIdle.anim, Assets/GameAssets/Player/PlayerAnimations/Harpoon/harpoonweapon.controller, Assets/GameAssets/Player/PlayerPrefabs/Harpoon.prefab
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-663
Fixed the issue of the animation moving the harpoon gun slightly over time. Animators shouldn't really move themselves. So to fix this I moved the animator 1 object up. You would think this is simple and takes 2 seconds. It does not. Animators hate it when you move their hierarchy. So I essentially just redid the animations using the old numbers. 
I did notice that the player doesn't holster the weapon when close to a wall. I remember that being a thing, but it isn't working. For the record I didn't break that, its like that in VS
Still think some of the animation triggers should be swapped out for bools but it's not my place to rework. If you do spam …
=> vs-eng-Harpoon-Gun-shifting-on-focus-spam-LV-663

Assets/GameAssets/Player/PlayerPrefabs/Harpoon.prefab, Assets/GameAssets/Player/PlayerScripts/Harpoon/HarpoonGun.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?customFilter=ari%3Acloud%3Ajira-software%3A792ff6f6-f5ba-4734-a1cd-457d34518a06%3Acustom-filter%2Factivation%2F489b3b11-a1a5-4c9e-afed-c8d621aa5e68%2F32%2F0ffdcf80-e13c-47e4-8c44-6b732fc8693c&selectedIssue=LV-939
The reload sfx used to play on the completion of the reload. Now it plays after a set duration after the reload start. Pretty simple
=> alpha-eng-Harpoon-reload-audio-is-delayed-LV-939

ProjectSettings/ProjectSettings.asset
checked "run in background" in build settings. I could not replicate the bug as described, even when testing extensively in build, but my research indicates this might be a potential fix.
=> Mouse does not appear in pause menu-931

Assets/GameAssets/Boss/BossScripts/Attacks/ProceduralAttack/ProceduralVine.cs
I changed the attack to triggerOnStay instead of OnEnter. It now has a cooldown after it resets from attacking which is currently only .2f before it attacks again. Viewable in scene "ProceduralTest"
=> LV-949-Monster-doesn-t-attack-after-first-ineraction

Assets/GameAssets/Boss/BossPrefabs/WeakPoints/WeakPoint.prefab, Assets/GameAssets/Player/PlayerPrefabs/HarpoonProjectile.prefab, ProjectSettings/TimeManager.asset
test in procedural test scene.
During my testing it seemed that 1/5 of the times I shot the head it would not detect it. I tried increasing the collision detection mode and also increasing the radius of the heads collider. This fixed all of nothing so I tried googling it and at the cost of some performance you can change the fixed timestep in project settings to a lower number and that seemed to do the trick
=> alpha-eng-Monster-Hitbox-Inconsistency-LV-961

Assets/GameAssets/World/WorldPrefabs/Mazes/Ending Chase Sequence.prefab
Updated the chase sequence prefabs with one ways on the end of the offshoots, ending hatch, crate piles to block the player,  normal attacks in the offshoots, and triggers for chase attack when they are finished by engineering. https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32?assignee=631f4a57978dae24dc064a89&selectedIssue=LV-1002
=> updated chase sequence prefabs

Assets/General/Scripts/Story/RandomizedAnimation.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-984
Tiny bug fix to remove a warning that would occur in the console
Code Review Estimation <1 Minute
In Engine Estimation <3 minutes
Where the warning would occur: Completion of any maze. When the maze switches from one to another. There are no warnings now
=> beta-eng-Tweening-Warning-in-regards-to-environmental-lights-LV-984

Assets/GameAssets/UI/UIAnimations/Health/HealthAnimations/Heart_Health_Controler.controller
In the heart animation settings, turned off the "has exit runtime" switch on each animation transition arrow.
Jira: https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32?customFilter=ari%3Acloud%3Ajira-software%3A792ff6f6-f5ba-4734-a1cd-457d34518a06%3Acustom-filter%2Factivation%2F489b3b11-a1a5-4c9e-afed-c8d621aa5e68%2F32%2Fe7f130a4-1698-4dfa-a009-a1806a05600f&selectedIssue=LV-990
=> LV-990-Beta-UI-Hayden_Fix_Runtime

Assets/GameAssets/UI/UIScripts/WorldSpace Popups.cs, Assets/GameAssets/World/WorldScripts/Interactables/HealthPackInteractable.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-987
Updated the health packs to change intractability based on if the player is full health or not. Best tested in the above deck scene. You shouldn't be able to use the health packs. Then open the debug menu (its bound to c) and inflict damage to yourself (you have to set the amount of damage first) Health packs heal 20 health currently, so if you inflict 30 damage you can use it twice.
Code Review Estimation: <3 minutes
Engine Review Estimation: <3 minutes
=> beta-eng-Can-use-healing-packs-at-full-health-LV-987

Assets/General/Prefabs/PlayerHUDCanvas.prefab, Assets/General/Scripts/Maze/MazeSubSceneManager.cs
The scene should no longer load in the next maze on top of the current maze when going to another subscene
IE: Settings or Quit
There might be errors beyond the first maze, but I'm exhausted and don't have the brain power to be on my laptop
=> Beta eng open pause and settings loads maze lv 1477

Assets/Prefabs/Managers/UniversalManagers/MainUniversalManagers/VfxManager.prefab, Assets/Scripts/Managers/UniversalManagers/MainUniversalManagers/VfxManager.cs, Assets/Scripts/WorldScripts/Interactables/HealthPackInteractable.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-1595
Healing from a health pack can now play vfx on the health pack. Its currently just using the steam vfx, which obviously does not make any sense in the context of healing, but this is the engineering side. Currently an issue relating to saving is making things act wonky. It might be easier to test this after that PR has already gone through and this has been updated off of that.
How to test: Use a health pack when hurt
Code Review Estimation: <2 minutes
In Engine Review Estimation: <5 minutes
=> gold-eng-Healing-VFX-Functionality-LV-1595

Assets/General/Audio/FMODScripts/FmodSfxEvents.cs, Assets/Scenes/BuildScenes/TitleScreen.unity, Assets/Scripts/MenuFunctionality/TitleScreenScrolling.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-1718
Pretty simple. There is functionality to play a sound effect on the main menu when it goes underwater. 
Currently there is no sound effect in the slot, but for testing feel free to temporarily add one
Code Review Estimation: <3 minutes
In Engine Review Estimation: <4 minutes
=> gold-eng-SFX-Trigger-for-Main-Menu-Moving-Down-LV-1718

Assets/Death.controller, Assets/Death.controller.meta, Assets/DeathAnimation.anim, Assets/DeathAnimation.anim.meta, Assets/Scenes/BuildScenes/DeathScreen.unity
Jira: https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32?assignee=61f6e440c6bd1a00691251d4&customFilter=ari%3Acloud%3Ajira-software%3A792ff6f6-f5ba-4734-a1cd-457d34518a06%3Acustom-filter%2Factivation%2F489b3b11-a1a5-4c9e-afed-c8d621aa5e68%2F32%2Fe7f130a4-1698-4dfa-a009-a1806a05600f&selectedIssue=LV-1508
A super light as a feather update. In the death screen, added an animation to the opacity to simulate a light flickering. Adding to the ambience. To test, just play the death scene.
=> Gold UI death UI light flicker lv 1508

Assets/Prefabs/PlayerPrefabs/PlayerKit.prefab, Assets/Scripts/PlayerScripts/PlayerCameraController.cs, Assets/Scripts/PlayerScripts/PlayerFunctionalityCore.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=712020%3A95314f55-18f3-4eed-888f-97f6fd939390&selectedIssue=LV-1625
Definitely ignore the fact Jira says this is a Charlie task. I am definitely Charlie, no doubt about it. Nothing suspicious. Anyway the issue on Jira is a bit vague so what this is fixing is that weird shake that happens when leaving a note if you are moving your mouse at the same time. I tried a bunch of different stuff to try to prevent it from happening, but I think it just comes down to the fact that cinemachine still reads the mouse inputs even when the camera isn't following. Best workaround I could find was to make the mouse be unable to be moved the moment the resume happens, and have it return to the base speed swiftly. If …
=> gold-eng-Mouse-Note-Bug-LV-1625

Assets/Art/3D/Windows/Materials/FakeFog.mat, Assets/Art/3D/Windows/Materials/LightShaft.mat, Assets/Prefabs/PlayerPrefabs/PlayerKit.prefab, Assets/Prefabs/WorldPrefabs/Window/FakeWindowContainer.prefab, Assets/Scripts/Maze/FakeWindowManager.cs, Assets/Scripts/Maze/FakeWindowObject.cs
Made window background darker to fit with the intro cutscene, fixed "black box" issue with the camera bounds
A few minor code changes:
- Got rid of the global registry/distance check in FakeWindowManager.cs since it just overcomplicated things
- Added an extra term in the view angle calculation to account for which direction the window is facing in world space (aka fixing the black box issue)
- Edited FakeWindowObject.cs to work with the changes in FakeWindowManager.cs
=> bug-window-asset-should-have-a-dark-skybox-like-the-title-screen-LV-1980

Assets/Prefabs/PauseMenuCanvas.prefab
Fixed pause menu freezing time
Death screen should not be affected/cause any problems
This should take about 10 minutes to test, because you have to make a build and go from the pause screen to the title screen
You can also try to die and go to title screen for an extra lil test, probably 5 more minutes
[Jira Link](https://bradleycapstone.atlassian.net/browse/LV-1979)
=> gold-eng-Resume-time-when-going-to-title-screen-LV-1979

Assets/Art/TechArt/WorldShaders/Water/WaterInterior.mat
Made some edits to the water material used in maze 2 to fix any visual glitches and make it look more like water than a translucent plane
=> gold-art-fix-water-shader-lv-1763

Assets/Scripts/PlayerScripts/PlayerFunctionalityCore.cs, Assets/Scripts/PlayerScripts/PlayerHealth.cs, Assets/Scripts/WorldScripts/Interactables/HealthPackInteractable.cs
https://bradleycapstone.atlassian.net/jira/software/projects/LV/boards/32/backlog?assignee=6318bb796856bdd60aa045de&selectedIssue=LV-2024
Med kit works properly now. Problem was that the med kit only updated if it could be used when the player took damage. If you have a medkit in a different maze segment it would be disabled when you got hit, then when you enter that segment since the medkit starts unable to be used it wouldn't update. Now when a medkit is enabled it checks what it's interaction status should be.
How to test: Easiest way is to get to maze 3 and use the medkit on the wall. (You gotta be damaged at least once first)
Code Review Estimation: <3 minutes
In Engine Review Estimation: <6 minutes
=> gold-eng-Medkit-doesn't-work-LV-2024

Assets/Art/Videos/DemoContextEdited.mp4.meta, Assets/Resources/SaveData/Data.json, Assets/Scripts/PlayerScripts/PlayerCameraController.cs
Yippee! I took the opportunity to fix some other bugs I noticed with the walking sway. Now it should work just fine. For this you just need to check a couple things:
- When you focus the harpoon gun, the gun stays on-center during the animation
- When you return from focusing (whether or not you shot), the walking sway starts again
- As you change movement direction without stopping, the walking sway only happens when you walk directly forward
Jira Task: https://bradleycapstone.atlassian.net/browse/LV-1998?atlOrigin=eyJpIjoiNDZjYTI0ZWNmMmFlNDM1OGJiYmI3MWU1Y2QwODlkYmYiLCJwIjoiaiJ9
Code Review Time: <3 minutes (there are some ghost changes that you can ignore)
In-Engine Review Time: <5 minutes
=> gold-eng-Harpoon-gun-displacement-LV-1998

Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaMaze.prefab
- adjusted triggers and transform values on monster spawns
- adjusted monster spawn speed from 5.5 to 2.5 which makes a new monster spawn as soon as the old one goes back into the hole
=> gold-des-Monster-Spawn-Updates-LV-2112

Assets/Scripts/Managers/UniversalManagers/MainUniversalManagers/RuntimeSfxManager.cs
Yippee! So thankfully Unity has some stuff that keeps track of whether or not the game is in focus. I just added one of those things where we handle the footsteps.
Jira Task: https://bradleycapstone.atlassian.net/browse/LV-1999?atlOrigin=eyJpIjoiNmJjZWU5ZDA4MjFhNDE2N2I2MGVjZGZiOWQ2MjEwZTgiLCJwIjoiaiJ9
Code Review Time: <1 minute
In-Engine Review Time: <5 minutes (just make a build, tab in and out of it, and make sure the footsteps don't play while you're out)
=> gold-eng-Player-footsteps-continue-when-the-player-tabs-out-LV-1999

Assets/Prefabs/WorldPrefabs/Mazes/Beta/ActualMazes/BetaNormalZone.prefab, Assets/Prefabs/WorldPrefabs/PlayerInteractables/InfiniteAmmoRack.prefab, Assets/Scenes/BuildScenes/MazeSubScenes/AdditiveMaze01.unity, Assets/Scenes/BuildScenes/MazeSubScenes/AdditiveMaze03.unity
Reenabled the interactable icon on the infinite ammo barrel. I am aware that the player cannot interact with the infinite ammo barrel in the first maze, that's the whole reason the interactable icons were disabled in the first place. Production decided that isn't getting fixed, they just wanted the issue with reloading fixed.
=> gold-qa-eng-unbreak-the-infinite-ammo-barrel
